### ISSUE TITLE
Android crash on getAudioDeviceStatusMap()

### ISSUE THREAD

**Issue by edolix** [zxcpoiu/react-native-incall-manager#77]
Hi @zxcpoiu , i'm working with latest commit because i need the fix made in 335540ebd7c399c4fec17b2d77b527ccdcf608ef .

My Android app crashes on this line: https://github.com/zxcpoiu/react-native-incall-manager/blob/7931e77cc16250b13eae66948a190fa0d50acca5/android/src/main/java/com/zxcpoiu/incallmanager/InCallManagerModule.java#L1908

with this exception from logcat:
```
D/InCallManager(22576): --- updateAudioDeviceState: wired headset=false, BT state=UNINITIALIZED
D/InCallManager(22576): Device status: available=[], selected=null, user selected=null
D/InCallManager(22576): setAudioDeviceInternal(device=NONE)
E/InCallManager(22576): specified audio device does not exist
D/InCallManager(22576): New device status: available=[EARPIECE, SPEAKER_PHONE], selected=NONE
E/AndroidRuntime(22576): FATAL EXCEPTION: mqt_native_modules
E/AndroidRuntime(22576): Process: com.swdemoapp, PID: 22576
E/AndroidRuntime(22576): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.zxcpoiu.incallmanager.InCallManagerModule$AudioDevice.name()' on a null object reference
E/AndroidRuntime(22576): 	at com.zxcpoiu.incallmanager.InCallManagerModule.getAudioDeviceStatusMap(InCallManagerModule.java:1908)
E/AndroidRuntime(22576): 	at com.zxcpoiu.incallmanager.InCallManagerModule.updateAudioDeviceState(InCallManagerModule.java:1890)
E/AndroidRuntime(22576): 	at com.zxcpoiu.incallmanager.InCallManagerModule.updateAudioRoute(InCallManagerModule.java:1602)
E/AndroidRuntime(22576): 	at com.zxcpoiu.incallmanager.InCallManagerModule.access$600(InCallManagerModule.java:69)
E/AndroidRuntime(22576): 	at com.zxcpoiu.incallmanager.InCallManagerModule$10.onPrepared(InCallManagerModule.java:1046)
E/AndroidRuntime(22576): 	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2760)
E/AndroidRuntime(22576): 	at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime(22576): 	at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime(22576): 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
E/AndroidRuntime(22576): 	at java.lang.Thread.run(Thread.java:818)
```

On RN side i start `InCallManager` like this:

```
InCallManager.start({ media: 'audio', ringback: '_DTMF_' })
```
it seems to be empty 
It seems that `newAudioDevice` is null on this line even though it should be `EARPIECE` by default. https://github.com/zxcpoiu/react-native-incall-manager/blob/7931e77cc16250b13eae66948a190fa0d50acca5/android/src/main/java/com/zxcpoiu/incallmanager/InCallManagerModule.java#L1880 

I added `android.permission.BLUETOOTH` permission but the issue persists.

Thanks!

**Comment by zxcpoiu** [comment]
Hi @edolix 

Thanks for your detailed explaination, should  be fixed via a9f31d2f8c2d0536f35713b02feb407115fba9c2
Please check again :+1:
